workspace 'TalkSDKSamples'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!
platform :ios, '12.0'

target 'TalkSDKSamples-Swift' do
	project 'TalkSDKSamples-Swift'
  	pod 'ZendeskTalkSDK', '3.1.1'
end

target 'TalkSDKSamples-ObjectiveC' do
	project 'TalkSDKSamples-ObjectiveC'
  	pod 'ZendeskTalkSDK', '3.1.1'
end
