workspace 'TalkSDKSamples'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!
platform :ios, '10.0'

target 'TalkSDKSamples-Swift' do
	project 'TalkSDKSamples-Swift'
  	pod 'ZendeskTalkSDK'
end

target 'TalkSDKSamples-ObjectiveC' do
	project 'TalkSDKSamples-ObjectiveC'
  	pod 'ZendeskTalkSDK'
end
