# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'ZDCChatAPI Sample App' do
  pod 'SDWebImage'
  pod 'DKImagePickerController', '4.1.7'
  pod 'DateToolsSwift'
  pod 'ZDCChat/API'
end
