# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZDCChatAPI Sample App' do
  pod 'SDWebImage', '~>3.8'
  pod 'DKImagePickerController'
  pod 'DateToolsSwift'
  pod 'ZDCChat/API', '1.3.5.1'
  pod 'Toaster', '~> 2.0.4'
end

