# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ZDCChatAPI Sample App' do
  pod 'SDWebImage', '~>3.8'
  pod 'DKImagePickerController'
  pod 'NSDate+TimeAgo'
  pod 'ZDCChat/API', '1.3.0.1'
  pod 'JLToast', '~> 1.4'
end

