# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'ZDCChatAPI Sample App' do
  pod 'SDWebImage'
  pod 'DKImagePickerController'
  pod 'DateToolsSwift'
  pod 'ZDCChat/API'
  pod 'Toaster'
end
