# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnswerBotSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnswerBotSample
	pod 'AnswerBotSDK', '1.0.0' 

end
